NOTE: To run the code, make sure all housing files are added to the colab files.

Problem 4 Matrix Report


In [18]:
import numpy as np

def generate_and_solve():
    results = []
    count = 0

    while count < 3:
        #creating random 3x3 matrix with certain range
        M = np.random.randint(-10, 11, size=(3, 3))

        #making sure the matrix is invertible
        if np.linalg.det(M) != 0:
            #inverse computation
            M_inv = np.linalg.inv(M)

            #matrix * inverse
            product = np.dot(M, M_inv)

            results.append((M, M_inv, product))
            count += 1

    return results

matrices_data = generate_and_solve()
matrices_data

[(array([[ -4,   3,   3],
         [-10,   6, -10],
         [  0,  10,   6]]),
  array([[-0.20481928, -0.01807229,  0.07228916],
         [-0.09036145,  0.03614458,  0.10542169],
         [ 0.15060241, -0.06024096, -0.00903614]]),
  array([[ 1.00000000e+00,  2.77555756e-17,  4.85722573e-17],
         [-2.22044605e-16,  1.00000000e+00, -1.38777878e-17],
         [-1.11022302e-16,  0.00000000e+00,  1.00000000e+00]])),
 (array([[ -2,   2,   6],
         [  4, -10,   9],
         [  7,   8,   5]]),
  array([[-0.12951168,  0.0403397 ,  0.08280255],
         [ 0.04564756, -0.0552017 ,  0.04458599],
         [ 0.10828025,  0.03184713,  0.01273885]]),
  array([[ 1.00000000e+00, -1.38777878e-17,  1.04083409e-17],
         [ 2.77555756e-17,  1.00000000e+00, -6.76542156e-17],
         [ 2.77555756e-17,  3.46944695e-17,  1.00000000e+00]])),
 (array([[  8, -10,   3],
         [ -7,   2,   1],
         [ -7,  -4,   5]]),
  array([[-0.33333333, -0.9047619 ,  0.38095238],
         [-0.66666667, -1.45

Problem 5

In [26]:
import pandas as pd

df = pd.read_csv('kc_house_data.csv')

#excluding 'id', 'date', and 'zipcode'.
columns_to_drop = ['id', 'date', 'zipcode']
df_cleaned = df.drop(columns=columns_to_drop, errors='ignore')

#outlining the dependant variable and features
response_col = 'price'
features = df_cleaned.drop(columns=[response_col])
response = df_cleaned[response_col]

#question 1, computing average, min, max, and variance
print("Question 1: Feature Statistics")

#computing stats for each column and putting them into a df
stats_df = pd.DataFrame()
stats_df['Average'] = features.mean()
stats_df['Min'] = features.min()
stats_df['Max'] = features.max()
stats_df['Variance'] = features.var()

print(stats_df)
print("\n")

#question 2, correlation coefficients of all features with price
print("Question 2: Correlation with Price")

#calculating correlation
correlations = features.corrwith(response)

#making it a df for table like display
correlation_table = pd.DataFrame(correlations, columns=['Correlation Coefficient'])

print(correlation_table)

Question 1: Feature Statistics
                    Average        Min           Max      Variance
bedrooms           3.370842     0.0000  3.300000e+01  8.650150e-01
bathrooms          2.114757     0.0000  8.000000e+00  5.931513e-01
sqft_living     2079.899736   290.0000  1.354000e+04  8.435337e+05
sqft_lot       15106.967566   520.0000  1.651359e+06  1.715659e+09
floors             1.494309     1.0000  3.500000e+00  2.915880e-01
waterfront         0.007542     0.0000  1.000000e+00  7.485226e-03
view               0.234303     0.0000  4.000000e+00  5.872426e-01
condition          3.409430     1.0000  5.000000e+00  4.234665e-01
grade              7.656873     1.0000  1.300000e+01  1.381703e+00
sqft_above      1788.390691   290.0000  9.410000e+03  6.857347e+05
sqft_basement    291.509045     0.0000  4.820000e+03  1.958727e+05
yr_built        1971.005136  1900.0000  2.015000e+03  8.627973e+02
yr_renovated      84.402258     0.0000  2.015000e+03  1.613462e+05
lat               47.560053    